saveFig = true;

[f1, s1, z1] = readSparamFile('TXBANTB.s1p');
[f2, s2, z2] = readSparamFile('TXBRXB.s1p');
[f3, s3, z3] = readSparamFile('ANTBRXB.s1p');

y = [min(min([s1, s2, s3])), max(max([s1, s2, s3]))];
f = [890, 915, 935, 960] * 1e6;
h = zeros(3, 1);

f11 = [find(f1 >= mean(f(3:4)), 1, 'first'), find(f1 <= mean(f(3:4)), 1, 'last')];
f22 = find(abs(s2) == max(abs(s2)), 1);
f33 = [find(f3 >= mean(f(1:2)), 1, 'first'), find(f3 <= mean(f(1:2)), 1, 'last')];

figure(1);
clf;
hold on;
for i = 1 : 4
    plot([f(i) f(i)] / 1e6, 20*log10(abs(y)) + 8 * [-1 1], 'k', 'linewidth', 1);
end
h(1) = plot(f1 / 1e6, 20*log10(abs(s1)), 'r', 'linewidth', 2);
h(2) = plot(f2 / 1e6, 20*log10(abs(s2)), 'k', 'linewidth', 2);
h(3) = plot(f3 / 1e6, 20*log10(abs(s3)), 'b', 'linewidth', 2);

plot(mean(f1(f11)) / 1e6, mean(20*log10(abs(s1(f11)))), 'ro', 'MarkerSize', 5, 'MarkerFaceColor', 'r');
plot(mean(f2(f22)) / 1e6, mean(20*log10(abs(s2(f22)))), 'ko', 'MarkerSize', 5, 'MarkerFaceColor', 'k');
plot(mean(f3(f33)) / 1e6, mean(20*log10(abs(s3(f33)))), 'bo', 'MarkerSize', 5, 'MarkerFaceColor', 'b');

arrow(  [f(1) / 1e6, 20*log10(abs(y(1))) - 4], ... 
        [f(2) / 1e6, 20*log10(abs(y(1))) - 4], ...
        'Ends', 'Both', 'Length', 10, 'BaseAngle', 75, 'TipAngle', 15);
arrow(  [f(3) / 1e6, 20*log10(abs(y(1))) - 4], ... 
        [f(4) / 1e6, 20*log10(abs(y(1))) - 4], ...
        'Ends', 'Both', 'Length', 10, 'BaseAngle', 75, 'TipAngle', 15);

text(	mean(f(1:2)/1e6), ...
		20*log10(abs(y(1))) - 12, ...
		'BS RX: $$890 - 915$$ MHz',...
		'HorizontalAlignment',  'center', ... 
		'Interpreter',          'latex', ...
		'BackgroundColor',      'w');
text(	mean(f(3:4)/1e6), ...
		20*log10(abs(y(1))) - 12, ...
		'BS TX: $$935 - 960$$ MHz' ,...
		'HorizontalAlignment',  'center', ... 
		'Interpreter',          'latex', ...
		'BackgroundColor',      'w');

text(	mean(f1(f11)) / 1e6 - 5, ...
		mean(20*log10(abs(s1(f11)))) + 10, ...
        sprintf('$$%.1f$$ dB, $$%.0f$$ MHz', ...
			mean(20*log10(abs(s1(f11)))), ...
			mean(f1(f11)) / 1e6) ,...
		'HorizontalAlignment',  'center', ... 
		'Interpreter',          'latex', ...
		'Color',                'r', ...
		'BackgroundColor',      'w');
text(	mean(f2(f22)) / 1e6 - 5, ...
		mean(20*log10(abs(s2(f22)))), ...
        sprintf('$$%.1f$$ dB, $$%.0f$$ MHz', ...
			mean(20*log10(abs(s2(f22)))), ...
			mean(f2(f22)) / 1e6) ,...
		'HorizontalAlignment',  'right', ... 
		'Interpreter',          'latex', ...
		'Color',                'k', ...
		'BackgroundColor',      'w');
text(   mean(f3(f33)) / 1e6 + 5, ...
        mean(20*log10(abs(s3(f33)))) + 10, ...
        sprintf('$$%.1f$$ dB, $$%.0f$$ MHz', ...
			mean(20*log10(abs(s3(f33)))), ...
			mean(f3(f33)) / 1e6) ,...
        'HorizontalAlignment',  'center', ... 
        'Interpreter',          'latex', ...
        'Color',                'b', ...
        'BackgroundColor',      'w');

hold off;
grid on;

set(gca, 'XTickMode', 'Manual');
set(gca, 'XTick', 850:10:1000);
set(gca, 'XTickLabel', ...
    cellfun(@num2str, {(850:10:1000)'}, 'UniformOutput', false));

title('GSM Basestation diplexer measurement', 'interpreter', 'latex');
ylabel('$$S_{12}$$ [dB]', 'interpreter', 'latex');
xlabel('$$f$$ [MHz]', 'interpreter', 'latex');

legend(h, {'$$\mathrm{TX_B \rightarrow ANT_B}$$', ...
	'$$\mathrm{TX_B \rightarrow RX_{B1}}$$', ...
	'$$\mathrm{ANT_B \rightarrow RX_{B1}}$$'}, ...
	'interpreter', 'latex');

if saveFig
exportfig(gcf, 'dpx.eps', ...
	'width',		18, ...
	'height',		10, ...
	'color',		'rgb', ...
	'resolution',	300, ...
	'LockAxes',		1, ...
	'FontMode',		'fixed', ...
	'FontSize',		9, ...
	'LineMode',		'scaled'	);
end
